name: Codebuild

on:
  pull_request:
    branches: [master]

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout PR branch
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: 3.7
    - uses: pre-commit/action@v2.0.0
      name: Run Hooks (black, flake8, etc.)
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Test with Pytest
      run: |
        pip install -r requirements-test.txt
        pytest
